config/routes.rb
CrunchStats::Application.routes.draw do
  get '/industries/new', controller: 'industries', action: 'new', as: 'new_industry'
  post '/industries', controller: 'industries', action: 'create'

  get '/industries', controller: 'industries', action: 'index', as: 'industries'
  get '/industries/:id', controller: 'industries', action: 'show', as: 'industry'

  get '/industries/:id/edit', controller: 'industries', action: 'edit', as: 'edit_industry'
  put '/industries/:id', controller: 'industries', action: 'update'

  delete '/industries/:id', controller: 'industries', action: 'destroy'

  get '/fundingrounds/new', controller: 'fundingrounds', action: 'new', as: 'new_fundinground'
  post '/fundingrounds', controller: 'fundingrounds', action: 'create'

  get '/fundingrounds', controller: 'fundingrounds', action: 'index', as: 'fundingrounds'
  get '/fundingrounds/:id', controller: 'fundingrounds', action: 'show', as: 'fundinground'

  get '/fundingrounds/:id/edit', controller: 'fundingrounds', action: 'edit', as: 'edit_fundinground'
  put '/fundingrounds/:id', controller: 'fundingrounds', action: 'update'

  delete '/fundingrounds/:id', controller: 'fundingrounds', action: 'destroy'

  get '/investments/new', controller: 'investments', action: 'new', as: 'new_investment'
  post '/investments', controller: 'investments', action: 'create'

  get '/investments', controller: 'investments', action: 'index', as: 'investments'
  get '/investments/:id', controller: 'investments', action: 'show', as: 'investment'

  get '/investments/:id/edit', controller: 'investments', action: 'edit', as: 'edit_investment'
  put '/investments/:id', controller: 'investments', action: 'update'

  delete '/investments/:id', controller: 'investments', action: 'destroy'

  get '/entities/new', controller: 'entities', action: 'new', as: 'new_entity'
  post '/entities', controller: 'entities', action: 'create'

  get '/entities', controller: 'entities', action: 'index', as: 'entities'
  get '/entities/:id', controller: 'entities', action: 'show', as: 'entity'

  get '/entities/:id/edit', controller: 'entities', action: 'edit', as: 'edit_entity'
  put '/entities/:id', controller: 'entities', action: 'update'

  delete '/entities/:id', controller: 'entities', action: 'destroy'

end

app/models/entity.rb
class Entity < ActiveRecord::Base
	belongs_to :industry

	has_many :investments
	has_many :funding_rounds, :through => :investments

end

app/models/fundinground.rb
class Fundinground < ActiveRecord::Base

	belongs_to :entity, :class_name => "Entity", :foreign_key => :entity_receiver_id

	has_many :investments
	has_many :entities, :through => :investments



end

app/models/industry.rb
class Industry < ActiveRecord::Base
end

app/models/investment.rb
class Investment < ActiveRecord::Base
	belongs_to :entity, :class_name => "Entity", :foreign_key => :entity_funding_id
	belongs_to :funding_round

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController

  def index
    @entities = Entity.all
  end

  def show
    @entity = Entity.find_by_id(params[:id])
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new
    @entity.name = params[:name]
    @entity.kind = params[:kind]
    @entity.location = params[:location]
    @entity.status = params[:status]
    @entity.perma = params[:perma]
    @entity.industry_id = params[:industry_id]
    
    if @entity.save
      redirect_to entities_url
    else
      render 'new'
    end
  end

  def edit
    @entity = Entity.find_by_id(params[:id])
  end

  def update
    @entity = Entity.find_by_id(params[:id])
    @entity.name = params[:name]
    @entity.kind = params[:kind]
    @entity.location = params[:location]
    @entity.status = params[:status]
    @entity.perma = params[:perma]
    @entity.industry_id = params[:industry_id]
    
    if @entity.save
      redirect_to entities_url
    else
      render 'new'
    end
  end

  def destroy
    @entity = Entity.find_by_id(params[:id])
    @entity.destroy
    redirect_to entities_url
  end
end

app/controllers/fundingrounds_controller.rb
class FundingroundsController < ApplicationController

  def index
    @fundingrounds = Fundinground.all
  end

  def show
    @fundinground = Fundinground.find_by_id(params[:id])
  end

  def new
    @fundinground = Fundinground.new
  end

  def create
    @fundinground = Fundinground.new
    @fundinground.series = params[:series]
    @fundinground.amount = params[:amount]
    @fundinground.currency = params[:currency]
    @fundinground.date = params[:date]
    @fundinground.entity_receiver_id = params[:entity_receiver_id]
    @fundinground.investment_id = params[:investment_id]
    
    if @fundinground.save
      redirect_to fundingrounds_url
    else
      render 'new'
    end
  end

  def edit
    @fundinground = Fundinground.find_by_id(params[:id])
  end

  def update
    @fundinground = Fundinground.find_by_id(params[:id])
    @fundinground.series = params[:series]
    @fundinground.amount = params[:amount]
    @fundinground.currency = params[:currency]
    @fundinground.date = params[:date]
    @fundinground.entity_receiver_id = params[:entity_receiver_id]
    @fundinground.investment_id = params[:investment_id]
    
    if @fundinground.save
      redirect_to fundingrounds_url
    else
      render 'new'
    end
  end

  def destroy
    @fundinground = Fundinground.find_by_id(params[:id])
    @fundinground.destroy
    redirect_to fundingrounds_url
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController

  def index
    @industries = Industry.all
  end

  def show
    @industry = Industry.find_by_id(params[:id])
  end

  def new
    @industry = Industry.new
  end

  def create
    @industry = Industry.new
    @industry.category = params[:category]
    
    if @industry.save
      redirect_to industries_url
    else
      render 'new'
    end
  end

  def edit
    @industry = Industry.find_by_id(params[:id])
  end

  def update
    @industry = Industry.find_by_id(params[:id])
    @industry.category = params[:category]
    
    if @industry.save
      redirect_to industries_url
    else
      render 'new'
    end
  end

  def destroy
    @industry = Industry.find_by_id(params[:id])
    @industry.destroy
    redirect_to industries_url
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController

  def index
    @investments = Investment.all
  end

  def show
    @investment = Investment.find_by_id(params[:id])
  end

  def new
    @investment = Investment.new
  end

  def create
    @investment = Investment.new
    @investment.entity_funding_id = params[:entity_funding_id]
    @investment.funding_round_id = params[:funding_round_id]
    
    if @investment.save
      redirect_to investments_url
    else
      render 'new'
    end
  end

  def edit
    @investment = Investment.find_by_id(params[:id])
  end

  def update
    @investment = Investment.find_by_id(params[:id])
    @investment.entity_funding_id = params[:entity_funding_id]
    @investment.funding_round_id = params[:funding_round_id]
    
    if @investment.save
      redirect_to investments_url
    else
      render 'new'
    end
  end

  def destroy
    @investment = Investment.find_by_id(params[:id])
    @investment.destroy
    redirect_to investments_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/edit.html.erb
<h1>Editing Entity #<%= @entity.id %></h1>


<%= form_tag(entity_url(@entity), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @entity.name %>
  </div>

  <div>
    <%= label_tag :kind %><br />
    <%= text_field_tag :kind, @entity.kind %>
  </div>

  <div>
    <%= label_tag :location %><br />
    <%= text_field_tag :location, @entity.location %>
  </div>

  <div>
    <%= label_tag :status %><br />
    <%= text_field_tag :status, @entity.status %>
  </div>

  <div>
    <%= label_tag :perma %><br />
    <%= text_field_tag :perma, @entity.perma %>
  </div>

  <div>
    <%= label_tag :industry_id %><br />
    <%= number_field_tag :industry_id, @entity.industry_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Entity" %>
  </div>

<% end %>

app/views/entities/index.html.erb
<h1>Entities</h1>

<p><%= link_to 'Add a New Entity', new_entity_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th>Location</th>
      <th>Status</th>
      <th>Perma</th>
      <th>Industry</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @entities.each do |entity| %>
    <tr>
      <td><%= entity.name %></td>
      <td><%= entity.kind %></td>
      <td><%= entity.location %></td>
      <td><%= entity.status %></td>
      <td><%= entity.perma %></td>
      <td><%= entity.industry_id %></td>
  
      <td><%= link_to 'Show', entity_url(entity) %></td>
      <td><%= link_to 'Edit', edit_entity_url(entity) %></td>
      <td><%= link_to 'Destroy', entity_url(entity), method: 'delete', data: { confirm: "Do you really want to delete this entity?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/entities/new.html.erb
<h1>New Entity</h1>


<%= form_tag(entities_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <div>
    <%= label_tag :kind %><br />
    <%= text_field_tag :kind %>
  </div>

  <div>
    <%= label_tag :location %><br />
    <%= text_field_tag :location %>
  </div>

  <div>
    <%= label_tag :status %><br />
    <%= text_field_tag :status %>
  </div>

  <div>
    <%= label_tag :perma %><br />
    <%= text_field_tag :perma %>
  </div>

  <div>
    <%= label_tag :industry_id %><br />
    <%= number_field_tag :industry_id %>
  </div>


  <div>
    <%= submit_tag "Create Entity" %>
  </div>
<% end %>

app/views/entities/show.html.erb
<h1>Entity #<%= @entity.id %></h1>

<p>
  <b>Name:</b>
  <%= @entity.name %>
</p>

<p>
  <b>Kind:</b>
  <%= @entity.kind %>
</p>

<p>
  <b>Location:</b>
  <%= @entity.location %>
</p>

<p>
  <b>Status:</b>
  <%= @entity.status %>
</p>

<p>
  <b>Perma:</b>
  <%= @entity.perma %>
</p>

<p>
  <b>Industry:</b>
  <%= @entity.industry_id %>
</p>

app/views/fundingrounds/edit.html.erb
<h1>Editing Fundinground #<%= @fundinground.id %></h1>


<%= form_tag(fundinground_url(@fundinground), method: 'put') do %>

  <div>
    <%= label_tag :series %><br />
    <%= text_field_tag :series, @fundinground.series %>
  </div>

  <div>
    <%= label_tag :amount %><br />
    <%= text_field_tag :amount, @fundinground.amount %>
  </div>

  <div>
    <%= label_tag :currency %><br />
    <%= text_field_tag :currency, @fundinground.currency %>
  </div>

  <div>
    <%= label_tag :date %><br />
    <%= text_field_tag :date, @fundinground.date %>
  </div>

  <div>
    <%= label_tag :entity_receiver_id %><br />
    <%= number_field_tag :entity_receiver_id, @fundinground.entity_receiver_id %>
  </div>

  <div>
    <%= label_tag :investment_id %><br />
    <%= number_field_tag :investment_id, @fundinground.investment_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Fundinground" %>
  </div>

<% end %>

app/views/fundingrounds/index.html.erb
<h1>Fundingrounds</h1>

<p><%= link_to 'Add a New Fundinground', new_fundinground_url %></p>

<table>
  <thead>
    <tr>
      <th>Series</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Date</th>
      <th>Entity receiver</th>
      <th>Investment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @fundingrounds.each do |fundinground| %>
    <tr>
      <td><%= fundinground.series %></td>
      <td><%= fundinground.amount %></td>
      <td><%= fundinground.currency %></td>
      <td><%= fundinground.date %></td>
      <td><%= fundinground.entity_receiver_id %></td>
      <td><%= fundinground.investment_id %></td>
  
      <td><%= link_to 'Show', fundinground_url(fundinground) %></td>
      <td><%= link_to 'Edit', edit_fundinground_url(fundinground) %></td>
      <td><%= link_to 'Destroy', fundinground_url(fundinground), method: 'delete', data: { confirm: "Do you really want to delete this fundinground?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/fundingrounds/new.html.erb
<h1>New Fundinground</h1>


<%= form_tag(fundingrounds_url, method: 'post') do %>


  <div>
    <%= label_tag :series %><br />
    <%= text_field_tag :series %>
  </div>

  <div>
    <%= label_tag :amount %><br />
    <%= text_field_tag :amount %>
  </div>

  <div>
    <%= label_tag :currency %><br />
    <%= text_field_tag :currency %>
  </div>

  <div>
    <%= label_tag :date %><br />
    <%= text_field_tag :date %>
  </div>

  <div>
    <%= label_tag :entity_receiver_id %><br />
    <%= number_field_tag :entity_receiver_id %>
  </div>

  <div>
    <%= label_tag :investment_id %><br />
    <%= number_field_tag :investment_id %>
  </div>


  <div>
    <%= submit_tag "Create Fundinground" %>
  </div>
<% end %>

app/views/fundingrounds/show.html.erb
<h1>Fundinground #<%= @fundinground.id %></h1>

<p>
  <b>Series:</b>
  <%= @fundinground.series %>
</p>

<p>
  <b>Amount:</b>
  <%= @fundinground.amount %>
</p>

<p>
  <b>Currency:</b>
  <%= @fundinground.currency %>
</p>

<p>
  <b>Date:</b>
  <%= @fundinground.date %>
</p>

<p>
  <b>Entity receiver:</b>
  <%= @fundinground.entity_receiver_id %>
</p>

<p>
  <b>Investment:</b>
  <%= @fundinground.investment_id %>
</p>

app/views/industries/edit.html.erb
<h1>Editing Industry #<%= @industry.id %></h1>


<%= form_tag(industry_url(@industry), method: 'put') do %>

  <div>
    <%= label_tag :category %><br />
    <%= text_field_tag :category, @industry.category %>
  </div>

  
  <div>
    <%= submit_tag "Update Industry" %>
  </div>

<% end %>

app/views/industries/index.html.erb
<h1>Industries</h1>

<p><%= link_to 'Add a New Industry', new_industry_url %></p>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @industries.each do |industry| %>
    <tr>
      <td><%= industry.category %></td>
  
      <td><%= link_to 'Show', industry_url(industry) %></td>
      <td><%= link_to 'Edit', edit_industry_url(industry) %></td>
      <td><%= link_to 'Destroy', industry_url(industry), method: 'delete', data: { confirm: "Do you really want to delete this industry?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/industries/new.html.erb
<h1>New Industry</h1>


<%= form_tag(industries_url, method: 'post') do %>


  <div>
    <%= label_tag :category %><br />
    <%= text_field_tag :category %>
  </div>


  <div>
    <%= submit_tag "Create Industry" %>
  </div>
<% end %>

app/views/industries/show.html.erb
<h1>Industry #<%= @industry.id %></h1>

<p>
  <b>Category:</b>
  <%= @industry.category %>
</p>

app/views/investments/edit.html.erb
<h1>Editing Investment #<%= @investment.id %></h1>


<%= form_tag(investment_url(@investment), method: 'put') do %>

  <div>
    <%= label_tag :entity_funding_id %><br />
    <%= number_field_tag :entity_funding_id, @investment.entity_funding_id %>
  </div>

  <div>
    <%= label_tag :funding_round_id %><br />
    <%= number_field_tag :funding_round_id, @investment.funding_round_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Investment" %>
  </div>

<% end %>

app/views/investments/index.html.erb
<h1>Investments</h1>

<p><%= link_to 'Add a New Investment', new_investment_url %></p>

<table>
  <thead>
    <tr>
      <th>Entity funding</th>
      <th>Funding round</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @investments.each do |investment| %>
    <tr>
      <td><%= investment.entity_funding_id %></td>
      <td><%= investment.funding_round_id %></td>
  
      <td><%= link_to 'Show', investment_url(investment) %></td>
      <td><%= link_to 'Edit', edit_investment_url(investment) %></td>
      <td><%= link_to 'Destroy', investment_url(investment), method: 'delete', data: { confirm: "Do you really want to delete this investment?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/investments/new.html.erb
<h1>New Investment</h1>


<%= form_tag(investments_url, method: 'post') do %>


  <div>
    <%= label_tag :entity_funding_id %><br />
    <%= number_field_tag :entity_funding_id %>
  </div>

  <div>
    <%= label_tag :funding_round_id %><br />
    <%= number_field_tag :funding_round_id %>
  </div>


  <div>
    <%= submit_tag "Create Investment" %>
  </div>
<% end %>

app/views/investments/show.html.erb
<h1>Investment #<%= @investment.id %></h1>

<p>
  <b>Entity funding:</b>
  <%= @investment.entity_funding_id %>
</p>

<p>
  <b>Funding round:</b>
  <%= @investment.funding_round_id %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrunchStats</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>